name: CI/CD

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install
        run: yarn

      # - name: Lint
      #   run: yarn ci:lint

      - name: Test Build
        run: yarn ci:test:build

      - name: Test Components
        run: yarn ci:test:core:components

      - name: Test Frontend
        run: yarn ci:test:frontend

      - name: Translations
        run: yarn manage:translations

      - name: Storybook
        run: yarn storybook:deploy-wallet
